In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[1]

2

In [5]:
b = np.array([[3, 4, 5], [10, 14, 15], [330, 100, 200]])

In [6]:
b[0]

array([3, 4, 5])

In [7]:
b[1]

array([10, 14, 15])

In [8]:
b[2]

array([330, 100, 200])

In [9]:
b[2,2]

200

In [10]:
b[2,1]

100

In [11]:
b[2][1]

100

In [12]:
b[:,1]

array([  4,  14, 100])

In [13]:
b[:,0]

array([  3,  10, 330])

In [14]:
b

array([[  3,   4,   5],
       [ 10,  14,  15],
       [330, 100, 200]])

In [15]:
c = np.array([
    [
        [2, 21], [3, 32]],
    [
        [4, 43], [5, 54]],
])

In [16]:
c[0]

array([[ 2, 21],
       [ 3, 32]])

In [17]:
c[0][0]

array([ 2, 21])

In [18]:
c[0][0][1]

21

In [19]:
d = np.zeros(3)

In [20]:
d

array([0., 0., 0.])

In [21]:
e = np.ones(6)

In [22]:
e

array([1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(4)

array([8.34427737e-308, 6.23040373e-307, 1.02360935e-306, 4.45061032e-308])

In [24]:
np.empty(3)

array([0., 0., 0.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.empty(4)

array([0., 0., 0., 0.])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [31]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.empty([5,4])

array([[7.70324230e-312, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.86921415e-306, 5.30276956e+180, 1.02941932e-071,
        6.97936820e-076],
       [5.06479219e-086, 3.35708706e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 2.42464163e-052,
        4.05620642e+174],
       [1.20743680e+161, 2.52871831e-052, 4.92350634e-143,
        1.50008929e+248]])

In [36]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(20, 50, 4)

array([20, 24, 28, 32, 36, 40, 44, 48])

In [38]:
np.full([5,5], 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [39]:
np.arange(200, 300, 3)

array([200, 203, 206, 209, 212, 215, 218, 221, 224, 227, 230, 233, 236,
       239, 242, 245, 248, 251, 254, 257, 260, 263, 266, 269, 272, 275,
       278, 281, 284, 287, 290, 293, 296, 299])

In [41]:
np.arange(201, 301, 3)

array([201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237,
       240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276,
       279, 282, 285, 288, 291, 294, 297, 300])

In [42]:
a

array([1, 2, 3])

In [43]:
aa = np.array([2, 3, 4, 5])

In [44]:
bb = np.array([10, 20, 30])

In [49]:
np.append(aa, bb)

array([ 2,  3,  4,  5, 10, 20, 30])

In [46]:
np.delete(aa,0)

array([3, 4, 5])

In [47]:
cc = np.array([4, 6, 2, 9, 7, 11])

In [48]:
np.sort(cc)

array([ 2,  4,  6,  7,  9, 11])

In [51]:
dd = np.array([[4, 8, 5], [13, 18, 27]])

In [52]:
dd

array([[ 4,  8,  5],
       [13, 18, 27]])

In [63]:
ee = np.array([[14, 37, 34], [35, 29, 41]])

In [64]:
ee

array([[14, 37, 34],
       [35, 29, 41]])

In [61]:
np.append(dd, ee)

array([ 4,  8,  5, 13, 18, 27, 14, 24, 34, 35, 39, 41])

In [65]:
np.append(dd, ee, axis=0)

array([[ 4,  8,  5],
       [13, 18, 27],
       [14, 37, 34],
       [35, 29, 41]])

In [66]:
np.append(dd, ee, axis=1)

array([[ 4,  8,  5, 14, 37, 34],
       [13, 18, 27, 35, 29, 41]])

In [70]:
np.flip(dd)

array([[27, 18, 13],
       [ 5,  8,  4]])

In [72]:
np.flip(np.sort(cc))

array([11,  9,  7,  6,  4,  2])

In [73]:
aa

array([2, 3, 4, 5])

In [74]:
a

array([1, 2, 3])

In [75]:
b

array([[  3,   4,   5],
       [ 10,  14,  15],
       [330, 100, 200]])

In [76]:
b.shape

(3, 3)

In [77]:
b.ndim

2

In [78]:
b.size

9

In [83]:
b.reshape(9, 1)

array([[  3],
       [  4],
       [  5],
       [ 10],
       [ 14],
       [ 15],
       [330],
       [100],
       [200]])

In [85]:
e

array([1., 1., 1., 1., 1., 1.])

In [91]:
f = np.array([[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7], [3, 4, 5, 6, 7, 8], [4, 5, 6, 7, 8, 9], [5, 6, 7, 8, 9, 10]])

In [92]:
f

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [93]:
f.reshape(3, 10)

array([[ 1,  2,  3,  4,  5,  6,  2,  3,  4,  5],
       [ 6,  7,  3,  4,  5,  6,  7,  8,  4,  5],
       [ 6,  7,  8,  9,  5,  6,  7,  8,  9, 10]])

In [94]:
e

array([1., 1., 1., 1., 1., 1.])

In [95]:
a

array([1, 2, 3])

In [96]:
b

array([[  3,   4,   5],
       [ 10,  14,  15],
       [330, 100, 200]])

In [97]:
g = a[np.newaxis]

In [98]:
g

array([[1, 2, 3]])

In [99]:
a.ndim

1

In [100]:
g.ndim

2

In [103]:
np.expand_dims(a, axis=0)

array([[1, 2, 3]])

In [104]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3]])

In [105]:
a

array([1, 2, 3])

In [108]:
h = np.arange(0, 101)

In [109]:
h

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [115]:
h[h > 40]

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [117]:
h[(h > 40) & (h % 2 == 0)]

array([ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,  66,
        68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,
        94,  96,  98, 100])

In [118]:
i = [[1, 1], [2, 2]]
j = [[3, 3], [4, 4]]
np.vstack((i, j))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [119]:
np.hstack((i, j))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [123]:
k = np.array([
    [11, 12, 13, 14, 15, 16],
    [22, 23, 24, 25, 26, 27],
    [33, 34, 35, 36, 37, 38],
    [44, 45, 46, 47, 48, 49]
])
np.hsplit(k, 3)

[array([[11, 12],
        [22, 23],
        [33, 34],
        [44, 45]]),
 array([[13, 14],
        [24, 25],
        [35, 36],
        [46, 47]]),
 array([[15, 16],
        [26, 27],
        [37, 38],
        [48, 49]])]

In [124]:
b

array([[  3,   4,   5],
       [ 10,  14,  15],
       [330, 100, 200]])

In [125]:
c

array([[[ 2, 21],
        [ 3, 32]],

       [[ 4, 43],
        [ 5, 54]]])

In [126]:
d

array([0., 0., 0.])

In [127]:
e

array([1., 1., 1., 1., 1., 1.])

In [128]:
aa

array([2, 3, 4, 5])

In [129]:
bb

array([10, 20, 30])

In [130]:
cc

array([ 4,  6,  2,  9,  7, 11])

In [131]:
dd

array([[ 4,  8,  5],
       [13, 18, 27]])

In [132]:
ee

array([[14, 37, 34],
       [35, 29, 41]])

In [133]:
dd.sum()

75

In [134]:
dd + ee

array([[18, 45, 39],
       [48, 47, 68]])

In [135]:
dd + 1

array([[ 5,  9,  6],
       [14, 19, 28]])

In [136]:
dd * 2

array([[ 8, 16, 10],
       [26, 36, 54]])

In [137]:
dd.sum(axis=0)

array([17, 26, 32])

In [138]:
dd.sum(axis=1)

array([17, 58])

In [141]:
dd.max()

27

In [142]:
ee.min()

14

In [143]:
ee.min(axis=0)

array([14, 29, 34])

In [144]:
ee.min(axis=1)

array([14, 29])

In [146]:
np.random.random((2, 5))

array([[0.33223913, 0.71076673, 0.84729053, 0.99964158, 0.53930061],
       [0.20368299, 0.35083893, 0.11796435, 0.41747101, 0.01669991]])

In [149]:
ff = np.random.random((2, 5))
ff * 100

array([[41.71829699, 26.09833261, 71.6546568 ,  1.93540058, 51.1533497 ],
       [59.40636608, 64.6746042 , 97.57395503, 45.81335357,  6.41850466]])

In [155]:
np.random.random((2, 5)) * 100

array([[57.40906734, 38.84470247, 99.92038025, 57.62605228, 75.41714478],
       [70.05409782, 11.58051181, 74.75100064, 22.37278726, 22.40863539]])